from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from datetime import datetime
import os

class ReportGenerator:
    """
    Generates a PDF report containing summaries, insights, and visualizations.
    """

    def generate_report(self, output_path, title, summary, keywords, sentiment, image_paths):
        """
        Builds and saves the PDF report.

        Args:
            output_path (str): File path for the output PDF.
            title (str): Title of the report.
            summary (str): Generated textual summary.
            keywords (list[str]): List of key phrases.
            sentiment (dict): Sentiment analysis results.
            image_paths (dict): Paths to generated visualization images.
        """
        # Create the PDF document object
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )

        # Container for the 'Flowable' objects
        story = []
        styles = getSampleStyleSheet()

        # Custom Styles
        title_style = styles['Title']
        heading_style = styles['Heading2']
        normal_style = styles['BodyText']
        
        # 1. Title Page
        story.append(Paragraph("InSightify Report", title_style))
        story.append(Paragraph(f"<b>Title:</b> {title}", styles['Heading3']))
        story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
        story.append(Spacer(1, 0.5 * inch))

        # 2. Executive Summary
        story.append(Paragraph("Executive Summary", heading_style))
        story.append(Paragraph(summary, normal_style))
        story.append(Spacer(1, 0.2 * inch))

        # 3. Key Insights (Keywords)
        story.append(Paragraph("Key Insights & Phrases", heading_style))
        
        # Keywords List
        keyword_items = [ListItem(Paragraph(k, normal_style)) for k in keywords[:10]]
        story.append(ListFlowable(keyword_items, bulletType='bullet', start='circle'))
        story.append(Spacer(1, 0.2 * inch))

        # 4. Sentiment Analysis
        story.append(Paragraph("Sentiment Analysis", heading_style))
        sent_text = f"<b>Label:</b> {sentiment.get('label', 'N/A')}<br/>" \
                    f"<b>Polarity:</b> {sentiment.get('polarity', 0)}<br/>" \
                    f"<b>Subjectivity:</b> {sentiment.get('subjectivity', 0)}"
        story.append(Paragraph(sent_text, normal_style))
        
        # Sentiment Chart
        if 'sentiment_chart' in image_paths and os.path.exists(image_paths['sentiment_chart']):
            story.append(Spacer(1, 0.1 * inch))
            img = Image(image_paths['sentiment_chart'], width=4*inch, height=4*inch)
            story.append(img)
        story.append(Spacer(1, 0.2 * inch))

        # 5. Visualizations
        story.append(Paragraph("Visual Data Analysis", heading_style))
        
        # Word Cloud
        if 'wordcloud' in image_paths and os.path.exists(image_paths['wordcloud']):
            story.append(Paragraph("Word Cloud", styles['Heading3']))
            img = Image(image_paths['wordcloud'], width=6*inch, height=3*inch)
            story.append(img)
            story.append(Spacer(1, 0.1 * inch))

        # Keyword Chart
        if 'keyword_chart' in image_paths and os.path.exists(image_paths['keyword_chart']):
            story.append(Paragraph("Top Keywords", styles['Heading3']))
            img = Image(image_paths['keyword_chart'], width=6*inch, height=3.5*inch)
            story.append(img)
            story.append(Spacer(1, 0.1 * inch))

        # Compression Chart
        if 'compression_chart' in image_paths and os.path.exists(image_paths['compression_chart']):
            story.append(Paragraph("Content Compression", styles['Heading3']))
            img = Image(image_paths['compression_chart'], width=4*inch, height=4*inch)
            story.append(img)

        # Footer / End
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph("<i>Generated by InSightify AI Engine</i>", styles['Italic']))

        # Build PDF
        doc.build(story)

if __name__ == "__main__":
    print("--- Running ReportGenerator Test ---")
    
    reporter = ReportGenerator()
    output_pdf = "tests/test_report.pdf"
    
    # Dummy Data
    dummy_title = "The Future of AI"
    dummy_summary = "Artificial Intelligence is transforming industries by automating tasks and providing deep insights. " \
                    "This report analyzes the impact of AI on modern technology."
    dummy_keywords = ["Artificial Intelligence", "Machine Learning", "Automation", "Deep Learning", "Neural Networks"]
    dummy_sentiment = {"label": "Positive", "polarity": 0.85, "subjectivity": 0.45}
    
    # Use images generated from Phase 5 test if available
    img_dir = "tests/viz_output"
    dummy_images = {
        "wordcloud": os.path.join(img_dir, "wordcloud.png"),
        "keyword_chart": os.path.join(img_dir, "keywords_bar.png"),
        "sentiment_chart": os.path.join(img_dir, "sentiment.png"),
        "compression_chart": os.path.join(img_dir, "compression.png")
    }
    
    reporter.generate_report(output_pdf, dummy_title, dummy_summary, dummy_keywords, dummy_sentiment, dummy_images)
    
    if os.path.exists(output_pdf):
        print(f"PDF generated successfully: {output_pdf}")
    else:
        print("Failed to generate PDF.")
    
    print("--- Test Complete ---")
